name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Test Report
      uses: actions/upload-artifact@v3
      with:
        name: SpringBoot Report               # Name of the folder
        path: target/site/jacoco/           # Path to test results
    - name: Login to Heroku Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:push -a ${{ vars.HEROKU_APP_NAME }} web
    - name: Release to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      run: heroku container:release -a ${{ vars.HEROKU_APP_NAME }} web
          
          
